#!/bin/bash

set -e

SOURCES="$(find *.py octodns_azion tests -name "*.py") $(grep --files-with-matches '^#!.*python' script/*)"

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

. "$VENV_NAME/bin/activate"

isort "$@" $SOURCES
black "$@" $SOURCES
